; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool on Sat Jul 21 2018 16:58:03 GMT-0400 (Eastern Daylight Time)
G91               ; relative positioning
M574 X1 S3
M915 X S2
M913 X75
G1 Z5 F6000 S2    ; lift Z relative to current position
G1 S1 X-538 F4000 ; move quickly to X axis endstop and stop there (first pass)
G1 X5 F6000       ; go back a few mm
G1 Z-5 F6000 S2   ; lower Z again
G90               ; absolute positioning