; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Sat Jul 21 2018 16:58:03 GMT-0400 (Eastern Daylight Time)
; Wait for set temperatures to be reached
M116 P0